version: "3.4"

services:
  api:
    image: my-first-project:v1
    container_name: my-first-project
    build:
      context: .
      dockerfile: 1 - Application/MyFirstProject.Api/Dockerfile
    ports:
      - "54237:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-api
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Abc123!@#"
      ACCEPT_EULA: "Y"